apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: eidas-configmap
  files:
  - config/demo/eidas.xml
  - config/demo/sp/sp.properties
  - config/demo/specificConnector/specificConnector.xml
  - config/demo/specificProxyService/specificProxyService.xml
  - config/demo/metadata/MetadataFetcher_Connector.properties
  - config/demo/metadata/MetadataFetcher_Service.properties
